name: gas
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 
      - name: sc1
        run: echo Hello, world!
      - name: multiple
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
